stages:
  load_data:
    cmd: python src/load_data.py
    deps:
      - src/load_data.py
    outs:
      - data/raw/data.csv

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/data.csv
    outs:
      - data/processed/data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/data.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
    metrics:
      - metrics/metrics.json
